### ISSUE TITLE
配置询问

### ISSUE THREAD

**Issue by unixc3t** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#1]
请问你这个主板是那个双网口的z390m,在Jd买的吗,如果在淘宝,可以告知购买店铺吗
请问你的主机机箱什么型号,cpu散热风扇型号,可以告知吗

**Comment by huijiewei** [comment]
我的电脑是去年配的

机箱是恩杰H210（挺一般的）
散热是大镰刀赤兔马（这个还行）

Asrock Z390m-ITX/ac 主板就这个型号。双网卡，不过我只用一个，另外一个没加载驱动

**Comment by unixc3t** [comment]
您用的是这个内存吧
美商海盗船(USCORSAIR) DDR4 2666 32GB 台式机内存条 复仇者LPX系列 
我把您仓库的配置啥的都拷贝过去是不是就安装就行了,我打算用和您一样的硬件
有需要改的地方吗

**Comment by huijiewei** [comment]
内存用频率3000+的

发自我的iPhone

在 2020年5月13日，18:08，rudy <notifications@github.com> 写道：

﻿

您用的是这个内存吧
美商海盗船(USCORSAIR) DDR4 2666 32GB 台式机内存条 复仇者LPX系列
我把您仓库的配置啥的都拷贝过去是不是就安装就行了,我打算用和您一样的硬件
有需要改的地方吗

**Comment by unixc3t** [comment]
请问这个机型选择怎么选 IMacPro7,1?

**Comment by huijiewei** [comment]
有核显不选 pro

发自我的iPhone

在 2020年5月17日，20:48，rudy <notifications@github.com> 写道：

﻿

请问这个机型选择怎么选 IMacPro7,1?

**Comment by divcss3** [comment]
如果你的 CPU 和我不一样，请到 Windows 下使用 SSDTTime 生成自己的 SSDT-PLUG.aml
---------------------------------
   这个意思是黑果主机要装个Windows，然后用SSDTTime生成SSDT-PLUG.aml吗？

**Comment by huijiewei** [comment]
> ## 如果你的 CPU 和我不一样，请到 Windows 下使用 SSDTTime 生成自己的 SSDT-PLUG.aml
> 这个意思是黑果主机要装个Windows，然后用SSDTTime生成SSDT-PLUG.aml吗？

方便的话就用 Windows 生成，不方便的自己手动编译一个或者在GITHUB搜索自己的CPU，找一个现成的。SSDT-PLUG.aml 生成方式多种多样。
