### ISSUE TITLE
长时间睡眠重启？

### ISSUE THREAD

**Issue by to2false** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#10]
老哥，有遇到过长时间睡眠就重启了的问题吗？
就是周期两天以上不唤醒过，下次唤醒进去其实已经是重启过了的，还有个report

**Comment by to2false** [comment]
睡眠唤醒操作是正常的

**Comment by huijiewei** [comment]
11.3 的时候遇到过，升级到 11.4 以后就没有遇到过了

**Comment by to2false** [comment]
我升到11.4也还是有问题，看崩溃日志也没看出来什么

**Comment by huijiewei** [comment]
我当时看也看不出什么

但是 Opencore 和 macOS 都升级最新版以后就没遇到过了

**Comment by to2false** [comment]
我换个usb口子好像没出现这个问题了
