### ISSUE TITLE
你会碰到偶尔启动黑屏的问题么？

### ISSUE THREAD

**Issue by wkj89** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#11]
偶发性的   黑屏强制关机在重启就好了

**Comment by huijiewei** [comment]
前一段时间我重新定制了 USB

然后全新安装了一下 Monterey

目前为止还没遇到过

**Comment by huijiewei** [comment]
去除 igfxfw=2 再试试效果

**Comment by huijiewei** [comment]
```sudo pmset tcpkeepalive 0```

设置以后睡眠黑屏问题完全解决
