### ISSUE TITLE
 5700xt该怎么调

### ISSUE THREAD

**Issue by recmess** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#12]
老兄，主板配置一样，就是CPU是i7-9700，显卡是蓝宝石5700xt，我把生成的PP_PhmSoftPowerPlayTable参数填进去，开机连盘符都没有，没法启动，是不是哪一步不对？

**Comment by huijiewei** [comment]
盘符没有是因为 ScanPolicy 不符合你的情况？先试试改成0，然后再自己定制 https://oc-scanpolicy.vercel.app/
