### ISSUE TITLE
50%的概率卡EB，找不到原因

### ISSUE THREAD

**Issue by feiying19802021** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#13]
冷启动90%的概率卡EB，热机重启30%的概率卡EB，不管是自己配置的OC，还是参照您的配置，都是如此，可能的原因是什么？

**Comment by feiying19802021** [comment]
![WechatIMG12](https://user-images.githubusercontent.com/86405495/151083766-8887c54b-b44a-44da-8625-f6190cdd894b.jpeg)

**Comment by huijiewei** [comment]
卡EB一般是 Above 4G 设置问题，如果没有使用3.70F版本的BIOS，请关闭这个选项，并设置 OC 的 ResizeAppleGpuBars 为 -1

**Comment by feiying19802021** [comment]
目前的4.3版本固件，要关掉Above 4G，并设置OC 的 ResizeAppleGpuBars 为 -1是吗？我测试一下，非常感谢您的指导

**Comment by huijiewei** [comment]
已增加说明
