### ISSUE TITLE
关于蓝牙问题咨询

### ISSUE THREAD

**Issue by muei** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#18]
先感谢提供的EFI。
我现在是同样的板子+CPU，没有独立显卡。
macOS为11版本时正常使用，现在升级到了13.
蓝牙失效，表现为蓝牙按钮点不了，无法发现设备。
置换了你的EFI，不能直接使用。
请教下怎么改

**Comment by liangsqrt** [comment]
估计要定制usb，我用这个efi隔空也不好使过，定制了usb后好了

**Comment by liangsqrt** [comment]
我尝试使用BlueToolFixup.kext, 加载后就没问题了
