### ISSUE TITLE
用着用着突然就黑屏关机，开关每按一下，风扇就嗡的猛转一下，马上就停，并不会开机。

### ISSUE THREAD

**Issue by liangsqrt** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#19]
我也是同样初版，cpu是8700k的；拿过来后不管是不调整，还是更改过ssdt和config，都是一开始好好的，慢慢地就开始突然黑屏关机，出现标题中的这种情况。遇到了这种情况连开机都开机不了，长按也不管用，只能断电。
一开始基本上不出现，随着时间推移，出现的频率越来越高，以至于到后边开机加载都没有加载完，就会黑屏了。奇怪的是断电一段时间后会这种情况会缓解一些，之后用着用着又会出现。

不知道有没有小伙伴遇到一样的情况的，还希望多多指点一下

**Comment by huijiewei** [comment]
你这个是8代CPU，试着改下核显的注入

更改 PciRoot(0x0)/Pci(0x1F,0x3) 相关注入
AAPL,ig-platform-id     data    <0300923e>

**Comment by liangsqrt** [comment]
wifi无线网卡上有颗螺丝不稳，拧紧了就没事了
