### ISSUE TITLE
技嘉5500xt实测稳定，跑分基本一致！

### ISSUE THREAD

**Issue by Good0007** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#2]
技嘉 RX 5500 XT Gaming OC 8GB
cpu: i5 9400
https://browser.geekbench.com/v5/compute/956094

metal:41367
openCL:39234

**Comment by Good0007** [comment]
用了个高码率的hevc测试视频（jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv）测试播放几秒钟就卡了（这个视频单核显如果加载了AppleGUC可以播放），用论坛魔改的那个weg可以播放（论坛魔改的跑分没有这个高），大佬给个联系方式一块交流下吧，我q:354867750

**Comment by huijiewei** [comment]
> 用了个高码率的hevc测试视频（jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv）测试播放几秒钟就卡了（这个视频单核显如果加载了AppleGUC可以播放），用论坛魔改的那个weg可以播放（论坛魔改的跑分没有这个高），大佬给个联系方式一块交流下吧，我q:354867750

你用什么播放器？IINA 不行，硬解太随缘了。我用 nPlayer 播放很正常

**Comment by Good0007** [comment]
额 正常了，开始忘了加那个参数加载AppleGuC了，核显没拉满，魔改weg不需要加，所以我换过来就忘了。下一步就换个拆机卡就完美了，1820a开机随机无法驱动，郁闷

**Comment by Good0007** [comment]
实测 vlc 解码能力比较强
