### ISSUE TITLE
AMD NAVI14 显卡驱动问题

### ISSUE THREAD

**Issue by acoffeeworld** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#3]
大佬,本人msi gaming X 5500xt.按照你AMD NAVI 核心显卡 PP_PhmSoftPowerPlayTable 参数生成方式,注入后.
1、显卡GeekBench5分数偏低OpenCL35000,Metal40000左右.
2、显卡PWM 35%,在大约60C时候,风扇转速特别慢,好像改完并没有预期效果.
Ps:能否给我个[https://github.com/huijiewei/ASRock-Z390m-ITX-ac-Opencore/tree/master/Resources/5500XT#amd-navi-%E6%A0%B8%E5%BF%83%E6%98%BE%E5%8D%A1-pp_phmsoftpowerplaytable-%E5%8F%82%E6%95%B0%E7%94%9F%E6%88%90%E6%96%B9%E5%BC%8F](url)这种的显卡优化跟详细抑或其他的方法,谢谢了~

**Comment by huijiewei** [comment]
PP_PhmSoftPowerPlayTable 我主要用来优化噪音，如果显卡没有噪音困扰就不需要注入

5500XT 这分数基本正常

发自我的iPhone

在 2020年7月7日，23:22，acoffeeworld <notifications@github.com> 写道：

﻿

大佬,本人msi gaming X 5500xt.按照你AMD NAVI 核心显卡 PP_PhmSoftPowerPlayTable 参数生成方式,注入后.
1、显卡GeekBench5分数偏低OpenCL35000,Metal40000左右.
2、显卡PWM 35%,在大约60C时候,风扇转速特别慢,好像改完并没有预期效果.
Ps:能否给我个https://github.com/huijiewei/ASRock-Z390m-ITX-ac-Opencore/tree/master/Resources/5500XT#amd-navi-%E6%A0%B8%E5%BF%83%E6%98%BE%E5%8D%A1-pp_phmsoftpowerplaytable-%E5%8F%82%E6%95%B0%E7%94%9F%E6%88%90%E6%96%B9%E5%BC%8F<url>这种的显卡优化跟详细抑或其他的方法,谢谢了~
