### ISSUE TITLE
SmallTreeIntel82576.kext missed?

### ISSUE THREAD

**Issue by wellmmc** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#4]
感谢一直维护！另外一块网卡是Intel I211，把SmallTreeIntel82576.kext集成就能用了。另外靠近PS/2接口的两个USB貌似不工作，兄弟有没有好的思路呢？

谢谢

**Comment by huijiewei** [comment]
我只用一块网卡上网，另外一块不用的话就不驱动了。

USB 口没办法，macOS 只支持15个端口。。必须要舍弃2个USB不用

**Comment by michael-kj** [comment]
> 我只用一块网卡上网，另外一块不用的话就不驱动了。
> 
> USB 口没办法，macOS 只支持15个端口。。必须要舍弃2个USB不用

借楼问一下，如果我没有独显的话 需要干什么操作呢？
然后我内存是32g的  这个需要改动什么配置么？

**Comment by huijiewei** [comment]
> > 我只用一块网卡上网，另外一块不用的话就不驱动了。
> > USB 口没办法，macOS 只支持15个端口。。必须要舍弃2个USB不用
> 
> 借楼问一下，如果我没有独显的话 需要干什么操作呢？
> 然后我内存是32g的 这个需要改动什么配置么？

更改机型为 Macmini8,1

更改 PciRoot(0x0)/Pci(0x1F,0x3) 相关注入
```
AAPL,ig-platform-id     data    <07009b3e>

device-id               data    <9b3e0000>

enable-hdmi20           data    <01000000>

framebuffer-unifiedmem  data    <00000080>
```

删除 DeviceProperties 下的 PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)

**Comment by michael-kj** [comment]
> > > 我只用一块网卡上网，另外一块不用的话就不驱动了。
> > > USB 口没办法，macOS 只支持15个端口。。必须要舍弃2个USB不用
> > 
> > 
> > 借楼问一下，如果我没有独显的话 需要干什么操作呢？
> > 然后我内存是32g的 这个需要改动什么配置么？
> 
> 更改机型为 Macmini8,1
> 
> 更改 PciRoot(0x0)/Pci(0x1F,0x3) 相关注入
> 
> ```
> AAPL,ig-platform-id     data    <07009b3e>
> 
> device-id               data    <9b3e0000>
> 
> enable-hdmi20           data    <01000000>
> 
> framebuffer-unifiedmem  data    <00000080>
> ```
> 
> 删除 DeviceProperties 下的 PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)

谢谢 我下周末在家试试  有问题再请教你  拜谢

**Comment by michael-kj** [comment]
> > > 我只用一块网卡上网，另外一块不用的话就不驱动了。
> > > USB 口没办法，macOS 只支持15个端口。。必须要舍弃2个USB不用
> > 
> > 
> > 借楼问一下，如果我没有独显的话 需要干什么操作呢？
> > 然后我内存是32g的 这个需要改动什么配置么？
> 
> 更改机型为 Macmini8,1
> 
> 更改 PciRoot(0x0)/Pci(0x1F,0x3) 相关注入
> 
> ```
> AAPL,ig-platform-id     data    <07009b3e>
> 
> device-id               data    <9b3e0000>
> 
> enable-hdmi20           data    <01000000>
> 
> framebuffer-unifiedmem  data    <00000080>
> ```
> 
> 删除 DeviceProperties 下的 PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)/Pci(0x0,0x0)

谢谢大佬  修改后   基本搞定  顺便写一点我的改动  以防别人需要：
HideAuxiliary   改为true  可以打开recovery
ScanPolicy  改成0  可以引导win linux


从clover换成OC后 蓝牙听歌 总觉得。。。声音怪怪的。。。是我心理作用？？？----》 well，最后发现是。。。我蓝牙耳机，左右带反了。。。笑哭
