### ISSUE TITLE
大佬，主板华硕B365M加独显蓝宝石RX5500XT遇到两个很奇怪的问题

### ISSUE THREAD

**Issue by cyixlq** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#5]
如题，装好黑苹果15.719H2后，第一个问题是独显HDMI输出无信号。第二个问题是配合核显实现硬解，试过Id 3e910003 3e980003。改好后第一下可以，重启后又卡死，感觉核显没驱动好，改下id或者机型又可以了，重启一下又不行。
大佬有遇到过嘛？

**Comment by huijiewei** [comment]
不知道你的配置，没法帮你
