### ISSUE TITLE
有没有碰到wifi在win10下不能工作的问题？

### ISSUE THREAD

**Issue by sunnylqm** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#6]
我的配置基本一致，除了cpu是10700k，ssd分别是samsung pm981a（mac）和Intel 665p（win）
碰到个问题就是win10下wifi驱动显示正常工作，但无法搜索到任何ssid，网上也有多人有这个问题
https://www.reddit.com/r/hackintosh/comments/imahd3/bcm94360cd_not_working_on_windows_10_working_in/

**Comment by huijiewei** [comment]
我的无线网卡是 BCM94360CS2

一切正常

**Comment by sunnylqm** [comment]
谢谢回复。我也是BCM94360CS2，但就是不工作。
顺便问下这套配置可以ota升级big sur吗？

**Comment by huijiewei** [comment]
BCM94360CS2 Windows 10 下面我用的是这个最新的驱动
https://necacom.net/index.php/broadcom/bcm-43/12423-broadcom-bcm-43xx-wireless-lan-drivers-version-7-77-119-0-whql

升级 Big Sur 没有问题，前几天就 OTA 升级了

**Comment by sunnylqm** [comment]
收到，谢谢，我试试

**Comment by sunnylqm** [comment]
驱动很顺利的装上了，但是还是搜不到任何网络
