### ISSUE TITLE
睡眠usb能正常唤醒吗？

### ISSUE THREAD

**Issue by to2false** [huijiewei/ASRock-Z390m-ITX-ac-Opencore#7]
我主板和u一样，仅部分差别替换成自己的kexts，一切功能正常

遇到问题的一个问题是，睡眠usb无法唤醒，电源键能正常唤醒

**Comment by huijiewei** [comment]
禁用 GPRW 补丁即可。

ACPI Add 里面 SSDT-GPRW.aml 禁用
ACPI Patch 里面 GPRW to XPRW 禁用

禁用后如果USB定制的不合适会造成睡眠既醒的问题。

**Comment by to2false** [comment]
十分有效，谢谢
